//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBSFundManager.FundsBlotter.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int Id { get; set; }
        public string StockName { get; set; }
        public Nullable<int> StockType { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> MarketValue { get; set; }
        public Nullable<decimal> TransactionCost { get; set; }
        public Nullable<decimal> StockWieght { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
