//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBSFundManager.FundsBlotter.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UBSFundsDBEntities : DbContext
    {
        public UBSFundsDBEntities()
            : base("name=UBSFundsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStockType> tblStockTypes { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
    
        public virtual ObjectResult<spGetAllFundsByUserId_Result> spGetAllFundsByUserId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllFundsByUserId_Result>("spGetAllFundsByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<spGetAllFundsSummary_Result> spGetAllFundsSummary(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllFundsSummary_Result>("spGetAllFundsSummary", userIdParameter);
        }
    }
}
